### ISSUE TITLE
Update tooling to check labels of new dynamic services

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/ci-service-integration-library#3]
### Problem
While building this new jupyter-chaste I had this issue: the image successfully built, but then, when trying to run it in a local deploy of oSPARC I got many errors.

This was because I had some settings labels missing. E.g. the `paths-mapping` and that was causing the service to be run via director_v0, if I understand that well.

And then I got this error:
```
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 140, in observing_single_service
    await _apply_observation_cycle(scheduler, scheduler_data)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 69, in _apply_observation_cycle
    await dynamic_scheduler_event.action(app, scheduler_data)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events.py", line 253, in action
    scheduler_data.service_port = extract_service_port_from_compose_start_spec(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/docker_service_specs/sidecar.py", line 25, in extract_service_port_from_compose_start_spec
    return parse_obj_as(int, create_service_params.Labels["service_port"])
```
I solved by adding the appropriate labels to `runtime.yml`.

### Definition of done
The tooling should be updated to check all the necessary labels while building new dynamic services (as discussed with @GitHK)

### How to test
This commit should fail building: https://github.com/ITISFoundation/jupyter-chaste/commit/f75c28ceebc1d96d7f3958aaee66ef3c7adb8734
(While it did not with the current version)

**Comment by GitHK** [comment]
That is correct. You are allowed not to specify the paths-mapping. For multiple image services this is a required feature.
The issue in your case was inadvertently creating a legacy service which did not run as expected
