### ISSUE TITLE
Retry if a github call temporarily fails

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/ci-service-integration-library#6]
I don't know what is the best approach to overcome this, but in the last weeks it happens more and more often that our internal publisher pipeline fails, because workflow runs cannot be retrieved (temporarily). See for instance [this pipeline](https://git.speag.com/oSparc/docker-publisher-osparc-services/-/pipelines/805211). 

What we see in the logs is, e.g.:
```
$ 'git ls-remote https://github.com/ITISFoundation/ML-TensorFlow-application refs/heads/main -q'
==================================================
GENERATED PIPELINE
==================================================
stages:
    - info
no-further-action-required:
    image: $CI_SERVICE_INTEGRATION_LIBRARY
    tags:
    stage: info
    tags:
        - DOCKER
        - XSERVER
        - GPU
        - LINUX
    script:
        - echo "Nothing required updates. No builds scheduled."
==================================================
Traceback (most recent call last):
  File "/.pyenv/versions/3.10.10/bin/dpos", line 33, in <module>
    sys.exit(load_entry_point('docker-publisher-osparc-services==0.0.1', 'console_scripts', 'dpos')())
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/docker_publisher_osparc_services/cli.py", line 129, in main
    asyncio.get_event_loop().run_until_complete(run_command(config))
  File "/.pyenv/versions/3.10.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/docker_publisher_osparc_services/cli.py", line 35, in run_command
    if not await did_ci_pass(repo_model, branch_hash):
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/docker_publisher_osparc_services/operations.py", line 47, in did_ci_pass
    return await github_did_last_repo_run_pass(repo_model, branch_hash)
  File "/.pyenv/versions/3.10.10/lib/python3.10/site-packages/docker_publisher_osparc_services/http_interface.py", line 28, in github_did_last_repo_run_pass
    for run in runs["workflow_runs"]:
KeyError: 'workflow_runs'
```

**Comment by wvangeit** [comment]
This is blocking me atm. Do we know by chance why this happens? Are we hitting some github api limits or so?

**Comment by wvangeit** [comment]
I saw that unauthenticated github API request are limited to 60/hour:
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28
That could be it? 
Maybe we should consider creating a github account for these request?

**Comment by GitHK** [comment]
This could be it, since we are sharing it with a big pool of users.
I can add the authentication options to aid you wit this.

**Comment by wvangeit** [comment]
Yeah, that would be great. I assume the 5000/hour would be enough, especially if we make dedicated users for each CI plan.

**Comment by GitHK** [comment]
added release v2.0.3 which should take care of this

**Comment by wvangeit** [comment]
👍🏻 thx!

**Comment by GitHK** [comment]
Pipeline was also updated and works with the new GitHub Token.

**Comment by wvangeit** [comment]
Works perfectly 🥇
